---
name: ci
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
jobs:
  # yamllint:
  #   uses: networkservicemesh/.github/.github/workflows/yamllint.yaml@main
  #   with:
  #     config_file: "./.yamllint.yml"

  shellcheck:
    uses: networkservicemesh/.github/.github/workflows/shellcheck.yaml@main

  golangci-lint:
    uses: networkservicemesh/.github/.github/workflows/golangci-lint.yaml@main

  excludeFmtErrorf:
    uses: networkservicemesh/.github/.github/workflows/exclude-fmt-errorf.yaml@main

  restrictNSMDeps:
    uses: networkservicemesh/.github/.github/workflows/restrict-nsm-deps.yaml@main
    with:
      allowed_repositories: "api, sdk, sdk-k8s, sdk-kernel, sdk-sriov, sdk-vpp, govpp, vpphelper"

  # checkgomod:
  #   uses: networkservicemesh/.github/.github/workflows/checkgomod.yaml@main

  gogenerate:
    uses: networkservicemesh/.github/.github/workflows/cmd-gogenerate.yaml@main

  excludereplace:
    uses: networkservicemesh/.github/.github/workflows/exclude-replace.yaml@main

  docker-build-and-test:
    if: github.repository != 'networkservicemesh/cmd-template'
    uses: networkservicemesh/.github/.github/workflows/docker-build-and-test.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: refs/heads/release/v1.11.1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "networkservicemesh"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "ghcr.io/networkservicemesh/cmd-forwarder-vpp:v1.11.1-fix.1"
 
  print-debug-info:
    name: Print debug info
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2